project:
  type: default
  render:
    - index.qmd
    - "lectures/*/index.qmd"

lang: bg

format:
  html:
    theme: [cosmo, theme/site.scss]
    toc: false
  revealjs:
    theme: [default, theme/nbu.scss]
    slide-number: c/t
    hash: true
    center: false
    transition: fade
    transition-speed: fast
    width: 1280
    height: 720
    margin: 0.1
    scrollable: true
    footer: "Икономически основи на бизнеса | НБУ"
